
on:
  push:
    branches: ['main']

jobs:
  build:
    name: Welcome Msg 
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: welcome msg
      run: |
        echo "welcome to the gitaction world :)"
    - name: printing workflow information
      run: |
        echo "Repo name: ${{ github.repository }}"
        echo "workspace name: ${{ github.workspace }}"
        ls ${{ github.workspace }}