
on:
  push:
    branches: ['main']

jobs:
  build:
    name: Welcome Msg 
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: welcome msg
      run: |
        echo "welcome to the gitaction world :)"
    - name: Display Repo information
      run: |
       echo "Repo name: ${{ github.repository }}"
       echo "Repo branch: ${{ github.brach }}"

    - name: printing workflow information
      run: |
        echo "workspace path: ${{ github.workspace }}"
        echo "workspace files inside workspace:"
        ls -la ${{ github.workspace }}